### ISSUE TITLE
Bug installing dependencies

### ISSUE THREAD

**Issue by yohang** [schmittjoh/php-code-analysis#12] opened 2012-10-01 12:33 UTC
When scheduling a full review, i've got this : 

```
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Oops, an internal error occurred.
It seems like there was an unrecoverable error when analyzing your dependencies. Please check your composer.json.
```

But when trying localy

```
$ git clone myproject
$ cd myproject
$ composer install --dev
```

All is ok, so my composer.json/lock seems ok.

**Comment by schmittjoh** [comment] 2012-10-01 12:56
Could you post the link to the review, I'll check this?

**Comment by yohang** [comment] 2012-10-01 12:57
Sure : http://jmsyst.com/reviews/e0fe8c55-1b07-4987-84e0-5fc8f318e90e

**Comment by schmittjoh** [comment] 2012-10-02 19:15
This was caused by a change in composer's format apparently, it should be fixed now if you run the review again.

**Closed as completed by schmittjoh** 2012-10-02 19:15 UTC
